#!/bin/bash

echo "🔧 Fixing npm permissions..."
echo "This script will help you fix npm permission issues."
echo ""
echo "You have two options:"
echo ""
echo "Option 1: Change ownership of npm cache (recommended)"
echo "Run this command with sudo:"
echo ""
echo "  sudo chown -R $(whoami):staff ~/.npm"
echo ""
echo "Option 2: Delete npm cache and start fresh"
echo "Run these commands with sudo:"
echo ""
echo "  sudo rm -rf ~/.npm"
echo "  mkdir ~/.npm"
echo ""
echo "After running either option, you can then run:"
echo "  npm install"
echo "  npm run dev"
echo ""
echo "The development server will run on port 7000 as configured."