#!/bin/bash

echo "🚀 AkemisFlow Dual Environment Setup - Step by Step"
echo "===================================================="
echo ""

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo -e "${BLUE}Step 1: Create Supabase Projects${NC}"
echo "=================================="
echo ""
echo "You need to create TWO Supabase projects:"
echo ""
echo "1. Go to: https://supabase.com/dashboard"
echo "2. Click 'New Project'"
echo "3. Create first project:"
echo "   - Name: akemisflow-prod"
echo "   - Generate database password (save it!)"
echo "   - Choose region closest to you"
echo ""
echo "4. Create second project:"
echo "   - Name: akemisflow-dev" 
echo "   - Generate different database password"
echo "   - Same region as production"
echo ""
echo "5. For EACH project, collect from Settings > API:"
echo "   - Project URL (https://xxxxx.supabase.co)"
echo "   - Anon/Public key"
echo "   - Service Role key"
echo ""
echo -e "${YELLOW}⏳ Create both projects first, then continue to Step 2${NC}"

echo ""
echo "================================================================="
echo -e "${BLUE}Step 2: Link Vercel Project${NC}"
echo "============================"
echo ""
echo "Run this command to link your Vercel project:"
echo ""
echo -e "${YELLOW}vercel login && vercel link${NC}"
echo ""
echo "Choose 'Link to existing project' and select 'akemisflow'"

echo ""
echo "================================================================="
echo -e "${BLUE}Step 3: Set Environment Variables${NC}"
echo "=================================="
echo ""
echo "Use these commands to set up environment variables:"
echo ""
echo -e "${YELLOW}# Production Environment Variables${NC}"
echo "vercel env add NEXT_PUBLIC_SUPABASE_URL production"
echo "vercel env add NEXT_PUBLIC_SUPABASE_ANON_KEY production"
echo "vercel env add SUPABASE_SERVICE_ROLE_KEY production"
echo "vercel env add DATABASE_URL production"
echo "vercel env add NEXTAUTH_URL production"
echo "vercel env add NEXTAUTH_SECRET production"
echo ""
echo -e "${YELLOW}# Preview Environment Variables (dev + features)${NC}"
echo "vercel env add NEXT_PUBLIC_SUPABASE_URL preview"
echo "vercel env add NEXT_PUBLIC_SUPABASE_ANON_KEY preview"
echo "vercel env add SUPABASE_SERVICE_ROLE_KEY preview"
echo "vercel env add DATABASE_URL preview"
echo "vercel env add NEXTAUTH_URL preview"
echo "vercel env add NEXTAUTH_SECRET preview"

echo ""
echo "================================================================="
echo -e "${BLUE}Step 4: Set Test Airwallex Credentials${NC}"
echo "======================================"
echo ""
echo "Set the test Airwallex credentials for preview environment:"
echo ""
echo -e "${YELLOW}echo \"ooSEP1J_RVCyQJCXMZx42g\" | vercel env add AIRWALLEX_CLIENT_ID preview --yes${NC}"
echo -e "${YELLOW}echo \"894d904d7c01237087c5b9b458003bfb8393e7b9638a1bf64c80bb6dc1b9df399d45c3a29e4eb6230592912c6bd489bb\" | vercel env add AIRWALLEX_API_KEY preview --yes${NC}"
echo -e "${YELLOW}echo \"https://api-demo.airwallex.com\" | vercel env add AIRWALLEX_BASE_URL preview --yes${NC}"

echo ""
echo "================================================================="
echo -e "${BLUE}Step 5: Set Environment Flags${NC}"
echo "============================="
echo ""
echo "Set environment type flags:"
echo ""
echo -e "${YELLOW}echo \"production\" | vercel env add NODE_ENV production --yes${NC}"
echo -e "${YELLOW}echo \"production\" | vercel env add AKEMIS_ENV production --yes${NC}"
echo -e "${YELLOW}echo \"development\" | vercel env add NODE_ENV preview --yes${NC}"
echo -e "${YELLOW}echo \"development\" | vercel env add AKEMIS_ENV preview --yes${NC}"

echo ""
echo "================================================================="
echo -e "${BLUE}Step 6: Setup Database Schemas${NC}"
echo "==============================="
echo ""
echo "Set up both database schemas:"
echo ""
echo -e "${YELLOW}# Production Database${NC}"
echo "export DATABASE_URL=\"your-prod-database-url\""
echo "pnpm prisma db push"
echo "node create-admin.js"
echo ""
echo -e "${YELLOW}# Development Database${NC}"
echo "export DATABASE_URL=\"your-dev-database-url\""
echo "pnpm prisma db push"  
echo "node create-admin.js"

echo ""
echo "================================================================="
echo -e "${BLUE}Step 7: Deploy Both Branches${NC}"
echo "============================="
echo ""
echo "Deploy both environments:"
echo ""
echo -e "${YELLOW}# Deploy production (master)${NC}"
echo "git checkout master"
echo "git push origin master"
echo ""
echo -e "${YELLOW}# Deploy development (dev)${NC}"
echo "git checkout dev"
echo "git merge master"
echo "git push origin dev"

echo ""
echo "================================================================="
echo -e "${GREEN}🎉 Setup Complete!${NC}"
echo "=================="
echo ""
echo "Your environments will be available at:"
echo "🏭 Production: https://akemisflow.vercel.app"
echo "🧪 Development: https://akemisflow-git-dev.vercel.app"
echo ""
echo "Login credentials (both environments):"
echo "📧 Email: philb75@gmail.com"
echo "🔑 Password: Philb123$"